# Generated by Django 5.1.15 on 2026-05-22 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(unique=True)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('n1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n5', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('n6', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bonus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', '판매중'), ('CLOSED', '추첨완료')], default='OPEN', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-round_no'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.PositiveSmallIntegerField()),
                ('n2', models.PositiveSmallIntegerField()),
                ('n3', models.PositiveSmallIntegerField()),
                ('n4', models.PositiveSmallIntegerField()),
                ('n5', models.PositiveSmallIntegerField()),
                ('n6', models.PositiveSmallIntegerField()),
                ('pick_type', models.CharField(choices=[('MANUAL', '수동'), ('AUTO', '자동')], max_length=6)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prize', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=1000)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
